# -*- mode: ruby -*-
# vi: set ft=ruby :

require "../include/vnode.rb"

=begin
* ONEBOX STAGING vTB Configuration
  - WEB
  - ORCH
  - DB
  - Zabbix
* CPU와 메모리 사용량에 따라 향후 scale up
=end

# Base NAT Port
BNP=1000

nat_map_default = {}
sync_folder_default = {}

node05 = Node.new("NODE05" , [], 2, 2048, nat_map_default, sync_folder_default, "em2")
node06 = Node.new("NODE06" , [], 2, 2048, nat_map_default, sync_folder_default, "em2")
node07 = Node.new("NODE07" , [], 2, 2048, nat_map_default, sync_folder_default, "em2")
node08 = Node.new("NODE08" , [], 2, 2048, nat_map_default, sync_folder_default, "em2")
node30 = Node.new("NODE30" , [], 2, 2048, nat_map_default, sync_folder_default, "em2")

# list of nodes and switches
nodes     = [ node05, node06, node07, node08, node30 ]
switches  = []  

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  create_switches(switches, config)
  create_nodes(nodes, config)  
end
