# -*- mode: ruby -*-
# vi: set ft=ruby :

require "../include/vnode.rb"

=begin
* OpenStack Kilo 버전 설치
  - 아무것도 없이 kilo만 설치
  - 스크립트도 필요없이 설치만 해보기
=end

# Base NAT Port
BNP=10000

nat_map_default = {}
nat_map_openstack = {"web" => { 80    => BNP+80 }, "novnc" => {6080 => BNP+6080}, "https" => {443 => BNP+443}}

sync_folder_default = {}
sync_folder_openstack = {}     

openstack   = Node.new("OpenStack"  , [1], 8, 8192, nat_map_openstack, sync_folder_openstack, "Intel(R) Centrino(R) Advanced-N 6235")
mgmt_sw     = Node.new("MGMT-SW"    , (1..6), 2, 2048, nat_map_default, sync_folder_default, "em2")

# list of nodes and switches
nodes     = [ openstack ]
switches  = []  

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  create_switches(switches, config)
  create_nodes(nodes, config)  
end
