# -*- mode: ruby -*-
# vi: set ft=ruby :

require "../include/vnode.rb"

=begin
* OpenStack Kilo 버전 설치
  - 아무것도 없이 kilo만 설치
  - 스크립트도 필요없이 설치만 해보기
* OpenStack Node Networking Configuration
  - eth0: NAT
  - eth1: MGMT
  - eth2: EXT
=end

# Base NAT Port
BNP=5000

nat_map_default = {}
nat_map_openstack = {"web" => { 80    => BNP+80 }}

sync_folder_default = {}
sync_folder_openstack = {}     

onebox = Node.new("One-Box" , [1], 8, 4096, nat_map_openstack, sync_folder_openstack, "p1p1")
client = Node.new("Client"  , [1], 2, 2048, nat_map_default, sync_folder_default)

# list of nodes and switches
nodes     = [ onebox, client]
switches  = []  

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  create_switches(switches, config)
  create_nodes(nodes, config)  
end
