# -*- mode: ruby -*-
# vi: set ft=ruby :

require "../include/vnode.rb"

=begin
* OneBox Agent Test
=end

# Base NAT Port
BNP=1010

nat_map_default = {}
sync_folder_default = {}

obagent  = Node.new("OneBox Agent"  , [], 4, 4096, nat_map_default, sync_folder_default, "em1")

# list of nodes and switches
nodes     = [ obagent ]
switches  = []  

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  create_switches(switches, config)
  create_nodes(nodes, config)  
end
